color0       #393940
color8       #9BA4A4
color1       #314F3E
color9       #314F3E
color2       #5A4E56
color10      #5A4E56
color3       #4A606B
color11      #4A606B
color4       #6A827A
color12      #6A827A
color5       #87A9B6
color13      #87A9B6
color6       #CCE6E7
color14      #CCE6E7
color7       #DDEAEB
color15      #DDEAEB